namespace tranoko
{
    partial class addHome
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.addressAdd = new Guna.UI2.WinForms.Guna2TextBox();
            this.searchButton = new Guna.UI2.WinForms.Guna2Button();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.townAdd = new Guna.UI2.WinForms.Guna2ComboBox();
            this.descripAdd = new Guna.UI2.WinForms.Guna2TextBox();
            this.priceAdd = new Guna.UI2.WinForms.Guna2NumericUpDown();
            this.categoryAdd = new Guna.UI2.WinForms.Guna2ComboBox();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.priceAdd)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(463, 40);
            this.panel1.TabIndex = 2;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Caviar Dreams", 15F, System.Drawing.FontStyle.Bold);
            this.label1.ForeColor = System.Drawing.Color.Yellow;
            this.label1.Location = new System.Drawing.Point(350, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(110, 26);
            this.label1.TabIndex = 0;
            this.label1.Text = "Add home";
            // 
            // addressAdd
            // 
            this.addressAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.addressAdd.BackColor = System.Drawing.SystemColors.Control;
            this.addressAdd.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.addressAdd.BorderThickness = 2;
            this.addressAdd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressAdd.DefaultText = "";
            this.addressAdd.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.addressAdd.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.addressAdd.DisabledState.ForeColor = System.Drawing.Color.Silver;
            this.addressAdd.DisabledState.Parent = this.addressAdd;
            this.addressAdd.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.addressAdd.FillColor = System.Drawing.SystemColors.Control;
            this.addressAdd.FocusedState.BorderColor = System.Drawing.Color.Yellow;
            this.addressAdd.FocusedState.Parent = this.addressAdd;
            this.addressAdd.FocusedState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.addressAdd.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.addressAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.addressAdd.HoverState.BorderColor = System.Drawing.Color.Yellow;
            this.addressAdd.HoverState.Parent = this.addressAdd;
            this.addressAdd.HoverState.PlaceholderForeColor = System.Drawing.Color.Yellow;
            this.addressAdd.Location = new System.Drawing.Point(108, 106);
            this.addressAdd.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.addressAdd.Name = "addressAdd";
            this.addressAdd.PasswordChar = '\0';
            this.addressAdd.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.addressAdd.PlaceholderText = "";
            this.addressAdd.SelectedText = "";
            this.addressAdd.ShadowDecoration.Parent = this.addressAdd;
            this.addressAdd.Size = new System.Drawing.Size(343, 28);
            this.addressAdd.Style = Guna.UI2.WinForms.Enums.TextBoxStyle.Material;
            this.addressAdd.TabIndex = 6;
            // 
            // searchButton
            // 
            this.searchButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.searchButton.BorderRadius = 10;
            this.searchButton.CheckedState.Parent = this.searchButton;
            this.searchButton.Cursor = System.Windows.Forms.Cursors.Hand;
            this.searchButton.CustomImages.Parent = this.searchButton;
            this.searchButton.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.searchButton.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.searchButton.ForeColor = System.Drawing.Color.White;
            this.searchButton.HoverState.Parent = this.searchButton;
            this.searchButton.Location = new System.Drawing.Point(271, 421);
            this.searchButton.Name = "searchButton";
            this.searchButton.ShadowDecoration.Parent = this.searchButton;
            this.searchButton.Size = new System.Drawing.Size(180, 45);
            this.searchButton.TabIndex = 10;
            this.searchButton.Text = "Add";
            this.searchButton.Click += new System.EventHandler(this.searchButton_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label3.Location = new System.Drawing.Point(70, 153);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(31, 17);
            this.label3.TabIndex = 12;
            this.label3.Text = "Prix";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label4.Location = new System.Drawing.Point(42, 106);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(60, 17);
            this.label4.TabIndex = 13;
            this.label4.Text = "Address";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label5.Location = new System.Drawing.Point(60, 55);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(42, 17);
            this.label5.TabIndex = 14;
            this.label5.Text = "Town";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label7.Location = new System.Drawing.Point(23, 250);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(79, 17);
            this.label7.TabIndex = 16;
            this.label7.Text = "Description";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.label6.Location = new System.Drawing.Point(36, 201);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(65, 17);
            this.label6.TabIndex = 15;
            this.label6.Text = "Category";
            // 
            // townAdd
            // 
            this.townAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.townAdd.BackColor = System.Drawing.Color.Transparent;
            this.townAdd.BorderRadius = 5;
            this.townAdd.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.townAdd.DropDownHeight = 400;
            this.townAdd.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.townAdd.FocusedColor = System.Drawing.Color.Empty;
            this.townAdd.FocusedState.Parent = this.townAdd;
            this.townAdd.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.townAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.townAdd.FormattingEnabled = true;
            this.townAdd.HoverState.Parent = this.townAdd;
            this.townAdd.IntegralHeight = false;
            this.townAdd.ItemHeight = 30;
            this.townAdd.Items.AddRange(new object[] {
            "Aboalimena",
            "Alakamisikely",
            "Alakamisy",
            "Alakamisy Ambohijato",
            "Alakamisy Ambohimaha",
            "Alakamisy Ambohimahazo",
            "Alakamisy Anativato",
            "Alakamisy Fenoarivo",
            "Alakamisy Itenina",
            "Alakamisy Marososona",
            "Alarobia",
            "Alarobia Bemaha",
            "Alarobia Vatosola",
            "Alasora",
            "Alatsinainikely",
            "Alatsinainy Ambazaha",
            "Alatsinainy Bakaro",
            "Alatsinainy Ialamarina",
            "Alatsinainy Ibity",
            "Ambahatrazo",
            "Ambahikily",
            "Ambahita",
            "Ambahive",
            "Ambahoabe",
            "Ambahy",
            "Ambakirano",
            "Ambakireny",
            "Ambakobe",
            "Ambalabe",
            "Ambalabe Befanjava",
            "Ambalahonko",
            "Ambalahosy Nord",
            "Ambalajia",
            "Ambalakely",
            "Ambalakida",
            "Ambalakindresy",
            "Ambalakirajy",
            "Ambalamahasoa",
            "Ambalamanakana",
            "Ambalamanasy II",
            "Ambalamidera II",
            "Ambalanirana",
            "Ambalanjanakomby",
            "Ambalaomby",
            "Ambalapaiso II",
            "Ambalaroka",
            "Ambalaromba",
            "Ambalarondra",
            "Ambalasatrana",
            "Ambalasoa",
            "Ambalatany",
            "Ambalavao",
            "Ambalavato",
            "Ambalavato Antevato",
            "Ambalavato Nord",
            "Ambalavero",
            "Ambalavolo",
            "Ambaliha",
            "Ambandrika",
            "Ambanisarika",
            "Ambanitsena",
            "Ambanizana",
            "Ambanja",
            "Ambanjabe",
            "Ambano",
            "Ambarakaraka",
            "Ambararata",
            "Ambararata Sofia",
            "Ambararatabe",
            "Ambararatabe Nord",
            "Ambarijeby Sud",
            "Ambarikorano",
            "Ambarimaninga",
            "Ambaripaika",
            "Ambato",
            "Ambato Ambarimay",
            "Ambatoabo",
            "Ambatoafo",
            "Ambatoasana Centre",
            "Ambatoben\"anjavy",
            "Ambatofahavalo",
            "Ambatofinandrahana",
            "Ambatofisaka II",
            "Ambatofitorahana",
            "Ambatofotsy",
            "Ambatoharanana",
            "Ambatolahy",
            "Ambatolampy",
            "Ambatolaona",
            "Ambatolava",
            "Ambatomainty",
            "Ambatomainty Atsimo",
            "Ambatomanga",
            "Ambatomanjaka",
            "Ambatomanoina",
            "Ambatomarina",
            "Ambatomena",
            "Ambatomiady",
            "Ambatomifanongoa",
            "Ambatomirahavavy",
            "Ambatomivary",
            "Ambatondrakalavao",
            "Ambatondrazaka",
            "Ambatondrazaka Suburbaine",
            "Ambatonikolahy",
            "Ambatoriha Est",
            "Ambatosia",
            "Ambatosoa",
            "Ambatosola",
            "Ambatosoratra",
            "Ambatotsipihina",
            "Ambatovola",
            "Ambatozavavy",
            "Ambatry Mitsinjo",
            "Ambavahaditokana",
            "Ambazoa",
            "Amberomanga",
            "Ambia",
            "Ambiky",
            "Ambila",
            "Ambilobe",
            "Ambilombe",
            "Ambinanidilana",
            "Ambinanifaho",
            "Ambinanin\"andravory",
            "Ambinanindovoka",
            "Ambinanindrano",
            "Ambinaninony",
            "Ambinaniroa",
            "Ambinanitelo",
            "Ambinanitromby",
            "Ambinany",
            "Amboaboa",
            "Amboanana",
            "Amboangibe",
            "Amboanjo",
            "Amboasary",
            "Amboasary Atsimo",
            "Amboasary Nord",
            "Amboavory",
            "Ambodiadabo",
            "Ambodiadabo M",
            "Ambodiamontana Kianga",
            "Ambodiampana",
            "Ambodiangezoka",
            "Ambodiara",
            "Ambodibonara",
            "Ambodifarihy Fenomanana",
            "Ambodiharina",
            "Ambodihazoambo",
            "Ambodilafa",
            "Ambodilazana",
            "Ambodimadiro",
            "Ambodimahabibo",
            "Ambodimanary",
            "Ambodimandresy",
            "Ambodimanga",
            "Ambodimanga I",
            "Ambodimanga II",
            "Ambodimanga Ramena",
            "Ambodimanga Rantabe",
            "Ambodimangavalo",
            "Ambodimotso Sud",
            "Ambodinonoka",
            "Ambodirian\"i Sahafary",
            "Ambodiriana",
            "Ambodisakoana",
            "Ambodisambalahy",
            "Ambodisikidy",
            "Amboditandroroho",
            "Amboditavolo",
            "Ambodivoananto",
            "Ambodivoangy",
            "Ambodivoanio",
            "Ambodivoara",
            "Ambodivongo",
            "Ambohibao Sud",
            "Ambohibary",
            "Ambohibary Vohilena",
            "Ambohibe",
            "Ambohiborona",
            "Ambohidranandriana",
            "Ambohidrapeto",
            "Ambohidratrimo",
            "Ambohidronono",
            "Ambohigogo",
            "Ambohijanahary",
            "Ambohijanaka",
            "Ambohimahamasina",
            "Ambohimahasoa",
            "Ambohimahavelona",
            "Ambohimahazo",
            "Ambohimalaza",
            "Ambohimalaza Miray",
            "Ambohimana",
            "Ambohimanambola",
            "Ambohimanana",
            "Ambohimanarina Marovazaha",
            "Ambohimandroso",
            "Ambohimandry",
            "Ambohimanga Du Sud",
            "Ambohimanga Rova",
            "Ambohimangakely",
            "Ambohimanjaka",
            "Ambohimarina",
            "Ambohimasina",
            "Ambohimena",
            "Ambohimiadana",
            "Ambohimiarina II",
            "Ambohimiarivo",
            "Ambohimiera",
            "Ambohimilanja",
            "Ambohimirary",
            "Ambohimisafy",
            "Ambohimitombo I",
            "Ambohimitombo II",
            "Ambohimitsinjo",
            "Ambohinamboarina",
            "Ambohinihaonana",
            "Ambohipaky",
            "Ambohipandrano",
            "Ambohipihaonana",
            "Ambohipo",
            "Ambohisoa",
            "Ambohitoaka",
            "Ambohitompoina",
            "Ambohitralanana",
            "Ambohitrambo",
            "Ambohitrandriamanitra",
            "Ambohitrandriana",
            "Ambohitrarivo",
            "Ambohitrimanjaka",
            "Ambohitrolomahitsy",
            "Ambohitromby",
            "Ambohitrony",
            "Ambohitsara Est",
            "Ambohitsara M",
            "Ambohitseheno",
            "Ambohitsilaozana",
            "Ambohitsimanova",
            "Ambolidibe Est",
            "Ambolobozo",
            "Ambolodia Sud",
            "Ambolofoty",
            "Ambolomadinika",
            "Ambolomoty",
            "Ambolotarakely",
            "Ambonaivo",
            "Ambondro",
            "Ambondromamy",
            "Ambondromisotra",
            "Ambondrona",
            "Ambongamarina",
            "Ambongo",
            "Amboriala",
            "Amborompotsy",
            "Amboronabo",
            "Amborondolo",
            "Amborondra",
            "Ambositra I",
            "Ambositra II",
            "Ambotaka",
            "Ambovombe",
            "Ambovombe Centre",
            "Ambovonomby",
            "Ampahana",
            "Ampahimanga",
            "Ampahitrosy",
            "Ampako",
            "Ampamata",
            "Ampanavoana",
            "Ampandrana",
            "Ampandriankilandy",
            "Ampandroantraka",
            "Ampanefena",
            "Ampanefy",
            "Ampaneva",
            "Ampangabe",
            "Ampangorina",
            "Ampanihy",
            "Ampanihy Ouest",
            "Ampanotokana",
            "Amparafaravola",
            "Amparaky",
            "Amparatanjona",
            "Amparibohitra",
            "Amparihintsokatra",
            "Amparihy",
            "Amparihy Est",
            "Ampary",
            "Ampasikely",
            "Ampasimadinika",
            "Ampasimadinika Manambolo",
            "Ampasimalemy",
            "Ampasimaneva",
            "Ampasimanjeva",
            "Ampasimatera",
            "Ampasimazava",
            "Ampasimbe",
            "Ampasimbe Manantsatrana",
            "Ampasimbe Onibe",
            "Ampasimboraka",
            "Ampasimena",
            "Ampasimpotsy Gara",
            "Ampasimpotsy Sud",
            "Ampasina Maningory",
            "Ampasinambo",
            "Ampasipotsy Mandialaza",
            "Ampasy Nahampoana",
            "Ampataka",
            "Ampatakamaroreny",
            "Ampatana Mandriankeniheny",
            "Ampefy",
            "Ampisikinana",
            "Ampisokina",
            "Ampitana",
            "Ampitatafika",
            "Ampitatsimo",
            "Ampohibe",
            "Ampondra",
            "Ampondralava",
            "Amporoforo",
            "Anaborano Ifasy",
            "Anahidrano",
            "Anakao",
            "Analaiva",
            "Analalava",
            "Analaliry",
            "Analamaho",
            "Analamary",
            "Analamisampy",
            "Analamitsivalana",
            "Analampasina",
            "Analapatsy",
            "Analaroa",
            "Analavoka",
            "Analavory",
            "Analila",
            "Anandravy",
            "Anandrivola",
            "Andabotoka",
            "Andaingo",
            "Andakana",
            "Andakatany",
            "Andalatanosy",
            "Andamasiny Vineta",
            "Andampy",
            "Andapa",
            "Andapafito",
            "Andara",
            "Andasibe",
            "Andasibe I",
            "Andekaleka",
            "Andemaka",
            "Andilamena",
            "Andilana Nord",
            "Andilanatoby",
            "Andimaky Manambolo",
            "Andina",
            "Andiolava",
            "Andohajango",
            "Andoharanofotsy",
            "Andoharanomaitso",
            "Andohariana",
            "Andolofotsy",
            "Andonabe",
            "Andonabe Sud",
            "Andondabe",
            "Andovoranto",
            "Andrafainkona",
            "Andrafiabe",
            "Andrahanjo",
            "Andrainjato",
            "Andrainjato Avaratra",
            "Andrainjato Centre",
            "Andrainjato Est",
            "Andrainjato Sud",
            "Andrakata",
            "Andramasina",
            "Andramy",
            "Andranambolava",
            "Andranoboka",
            "Andranobolaha",
            "Andranobory",
            "Andranofanjava",
            "Andranofasika",
            "Andranofito",
            "Andranofotsy",
            "Andranohinaly",
            "Andranolalina",
            "Andranolava",
            "Andranomafana",
            "Andranomamy",
            "Andranomanelatra",
            "Andranomangatsiaka",
            "Andranomavo",
            "Andranomena",
            "Andranomeva",
            "Andranomiady",
            "Andranomiditra",
            "Andranonahoatra",
            "Andranopasy",
            "Andranovao",
            "Andranovelona",
            "Andranovondronina",
            "Andranovorivato",
            "Andranovory",
            "Andratamarina",
            "Andravola Vohipeno",
            "Andravory",
            "Andrea",
            "Andreba",
            "Andrebakely Nord",
            "Andrebakely Sud",
            "Andrembesoa",
            "Andrembona",
            "Andriambilany",
            "Andriamena",
            "Andriandampy",
            "Andriba",
            "Andribavontsona",
            "Androhibe",
            "Androka",
            "Andromba",
            "Androndrono",
            "Androrangavola",
            "Androvakely",
            "Androy",
            "Angoaka Sud",
            "Angodongodona",
            "Anilobe",
            "Anivorano Est",
            "Anivorano Mitsinjo",
            "Anivorano Nord",
            "Anja Nord",
            "Anjahamana",
            "Anjahambe",
            "Anjahana",
            "Anjalazala",
            "Anjampaly",
            "Anjanadoria",
            "Anjanazana",
            "Anjangoveratra",
            "Anjeky Ankilikira",
            "Anjepy",
            "Anjeva Gara",
            "Anjiabe",
            "Anjiabe Ambony",
            "Anjiajia",
            "Anjialava",
            "Anjialavabe",
            "Anjiamangirana",
            "Anjinjaomby",
            "Anjoma",
            "Anjoma Betoho",
            "Anjoma Itsara",
            "Anjoma Nandihizana",
            "Anjoma Ramartina",
            "Anjoman\"ankona",
            "Anjozorobe",
            "Anjozoromadosy",
            "Ankadikely Ilafy",
            "Ankadimanga",
            "Ankadinandriana",
            "Ankadinondry Sakay",
            "Ankafina Tsarafidy",
            "Ankalalobe",
            "Ankaramena",
            "Ankaramy",
            "Ankarana Miraihina",
            "Ankaranabo Nord",
            "Ankaranana",
            "Ankaraobato",
            "Ankariera",
            "Ankarimbary",
            "Ankarimbelo",
            "Ankarinarivo Manirisoa",
            "Ankarinoro",
            "Ankaromalaza Mifanasoa",
            "Ankarongana",
            "Ankasakasa Tsibiray",
            "Ankatafa",
            "Ankatafana",
            "Ankavandra",
            "Ankazoabo Sud",
            "Ankazoambo",
            "Ankazobe",
            "Ankazomanga Ouest",
            "Ankazombalala",
            "Ankazomborona",
            "Ankazomiriotra",
            "Ankazondandy",
            "Ankazotokana",
            "Ankazotsifantatra",
            "Ankazovelo",
            "Ankerana",
            "Ankerana Avaratra",
            "Ankerika",
            "Anketrakabe",
            "Ankiabe-Salohy",
            "Ankiakabe Nord",
            "Ankiakabe-Fonoko",
            "Ankijabe",
            "Ankiliabo",
            "Ankililoaka",
            "Ankilimalinike",
            "Ankilimivory",
            "Ankilivalo",
            "Ankilizato",
            "Ankily",
            "Ankingameloka",
            "Ankirihiry",
            "Ankirihitra",
            "Ankiririky",
            "Ankiroroky",
            "Ankisabe",
            "Ankisatra",
            "Ankofa",
            "Ankofabe",
            "Ankondromena",
            "Ankotrofotsy",
            "Anoloka",
            "Anontsibe Centre",
            "Anorombato",
            "Anorontsangana",
            "Anororo",
            "Anosiala",
            "Anosiarivo I",
            "Anosiarivo Manapa",
            "Anosibe An\"ala",
            "Anosibe Ifanja",
            "Anosibe Ifody",
            "Anosibe Trimoloharano",
            "Anosimena",
            "Anosimparihy",
            "Anosinalainolona",
            "Anosivelo",
            "Anosizato Andrefana",
            "Anosy",
            "Anosy Tsararafa",
            "Anoviara",
            "Antafiambotry",
            "Antakasina",
            "Antakavana",
            "Antakotako",
            "Antalaha Ambonivohitra",
            "Antaly",
            "Antambohobe",
            "Antambolo",
            "Antanamalaza",
            "Antanambao",
            "Antanambao Ambary",
            "Antanambao Andranolava",
            "Antanambao Mahatsara",
            "Antanambao Manampontsy",
            "Antanambaobe",
            "Antanambaon\"amberina",
            "Antanambe",
            "Antanamitarana",
            "Antananabo",
            "Antananambo",
            "Antanananivo",
            "Antanandava",
            "Antanandehibe",
            "Antananivo Haut",
            "Antandrokomby",
            "Antanetibe",
            "Antanetikely",
            "Antaniditra",
            "Antanifotsy",
            "Antanimandry",
            "Antanimasaka",
            "Antanimbaribe",
            "Antanimbary",
            "Antanimena Onilahy",
            "Antanimenabaka",
            "Antanimieva",
            "Antanimora Atsimo",
            "Antaninarenina",
            "Antaretra",
            "Antaritarika",
            "Antehiroka",
            "Antenimbe",
            "Antenina",
            "Antetezambaro",
            "Anteza",
            "Antindra",
            "Antoby Est",
            "Antodinga",
            "Antoetra",
            "Antohabato",
            "Antohobe",
            "Antokonala",
            "Antombana",
            "Antondabe",
            "Antongo Vaovao",
            "Antongomena Bevary",
            "Antonibe",
            "Antotohazo",
            "Antranokarany",
            "Antsahabe",
            "Antsahafilo",
            "Antsahalalina",
            "Antsahalava",
            "Antsahamena",
            "Antsahampano",
            "Antsahanoro",
            "Antsahavaribe",
            "Antsaidoha Bebao",
            "Antsakabary",
            "Antsakanalabe",
            "Antsakoamanondro",
            "Antsakoamaro",
            "Antsalaka",
            "Antsalova",
            "Antsamaka",
            "Antsambaharo",
            "Antsambalahy",
            "Antsampandrano",
            "Antsampanimahazo",
            "Antsangasanga",
            "Antsaravibe",
            "Antsatramidola",
            "Antsatsaka",
            "Antsavoa",
            "Antsenakely Andraikiba",
            "Antsenavolo",
            "Antseranambe",
            "Antseza",
            "Antsiafabositra",
            "Antsiatsiaka",
            "Antsindra",
            "Antsirabe",
            "Antsirabe Afovoany Atsinanana",
            "Antsirabe Centre",
            "Antsirabe Nord",
            "Antsirabe Sahatany",
            "Antsoatany",
            "Antsoha",
            "Antsohihy",
            "Antsohimbondrona",
            "Antsondrodava",
            "Antsoso",
            "Arivonimamo I",
            "Arivonimamo II",
            "Avaratsena",
            "Basibasy",
            "Beahitse",
            "Bealampona",
            "Bealanana",
            "Beampombo I",
            "Beampombo II",
            "Beanana",
            "Beandrarezona",
            "Beantake",
            "Bebaboky Sud",
            "Bedidy",
            "Befandefa",
            "Befandriana Nord",
            "Befandriana Sud",
            "Befasy",
            "Befeta",
            "Befody",
            "Beforona",
            "Befotaka",
            "Befotaka Nord",
            "Befotaka Sud",
            "Begogo",
            "Behabobo",
            "Behara",
            "Beharena",
            "Beharona",
            "Behazomaty",
            "Beheloka",
            "Behenjy",
            "Behisatsy",
            "Behompy",
            "Bejofo",
            "Bekapaika",
            "Bekaraoky",
            "Bekatra",
            "Bekipay",
            "Bekitro",
            "Bekobay",
            "Bekodoka",
            "Bekofafa Sud",
            "Bekopaka",
            "Bekoratsaka",
            "Bekorobo",
            "Belafike Haut",
            "Belalanda",
            "Belambo",
            "Belambo Firaisana",
            "Belamoty",
            "Belanitra",
            "Belaoka Lokoho",
            "Belaoka Marovato",
            "Belavabary",
            "Belazao",
            "Belemoka",
            "Belindo Mahasoa",
            "Belinta",
            "Belitsaky",
            "Belo Sur Mer",
            "Belo Sur Tsiribihina",
            "Belobaka",
            "Beloha",
            "Bema",
            "Bemaharivo",
            "Bemahatazana",
            "Bemaitso",
            "Bemanevika",
            "Bemaneviky Haut Sambirano",
            "Bemaneviky Ouest",
            "Bemanondrobe",
            "Bemanonga",
            "Bemarivo",
            "Bemarivo Ankirondro",
            "Bemasoandro",
            "Bemavo",
            "Bemokotra",
            "Bemokotra Sud",
            "Benato Toby",
            "Benavony",
            "Benenitra",
            "Beraketa",
            "Beramanja",
            "Beratsimanina",
            "Beravina",
            "Bereketa",
            "Berenty",
            "Beretra Bevoay",
            "Berevo",
            "Berevo/ranobe",
            "Beroboka Nord",
            "Beronono",
            "Beroroha",
            "Beroy Atsimo",
            "Besakoa",
            "Besalampy",
            "Besely",
            "Besoa",
            "Betafo",
            "Betaimboay",
            "Betampona",
            "Betanatanana",
            "Betania",
            "Betanty Faux Cap",
            "Betaramahamay",
            "Betatao",
            "Beteza",
            "Betioky Atsimo",
            "Betrandraka",
            "Betroka",
            "Betsako",
            "Betsakotsako Andranotsara",
            "Betsiaka",
            "Betsimisotra",
            "Betsinjaka",
            "Betsipolitra",
            "Betsizaraina",
            "Betsohana",
            "Bevata",
            "Bevato",
            "Bevitiky",
            "Bevoay",
            "Bevonotra",
            "Bezaha",
            "Boanamary",
            "Bobakilandy",
            "Bobakindro",
            "Bobasakoa",
            "Bongatsara",
            "Brickaville",
            "Brieville",
            "Camp Robin",
            "Cu Morombe",
            "Dabolava",
            "Daraina",
            "Didy",
            "Diego Suarez",
            "Djangoa",
            "Doany",
            "Dondona",
            "Dzamandzar",
            "Ebelo",
            "Efatsy",
            "Ehara",
            "Ejeda",
            "Elonty",
            "Emagnobo",
            "Enakara-Haut",
            "Enaniliha",
            "Erada",
            "Esira",
            "Etrotroka Atsimo",
            "Evato",
            "Fahizay",
            "Fanambana",
            "Fanandrana",
            "Fanasana",
            "Fandrandava",
            "Fandriana",
            "Fanjakana",
            "Farafangana",
            "Farahalana",
            "Faratsiho",
            "Faravohitra",
            "Fasintsara",
            "Fenerive Est",
            "Fenoambany",
            "Fenoandala",
            "Fenoarivo",
            "Fenoarivo Centre",
            "Fenoevo-Efita",
            "Fenomby",
            "Feramanga Nord",
            "Fetraomby",
            "Fiadanana",
            "Fiaferana",
            "Fidirana",
            "Fierenana",
            "Fihaonana",
            "Fiombonana",
            "Firavahana",
            "Fitampito",
            "Fito",
            "Fitsinjovana Bakaro",
            "Fort-Dauphin",
            "Fotadrevo",
            "Fotivolo",
            "Fotsialanana",
            "Gogogogo",
            "Hell-Ville",
            "Iaboakoho",
            "Iabohazo",
            "Iaborotra",
            "Iakora",
            "Ialananindro",
            "Iamborano",
            "Iamonta",
            "Ianabinda",
            "Ianakafy",
            "Ianapera",
            "Iara",
            "Iarinarivo",
            "Iarintsena",
            "Iavonomby Vohibola",
            "Ifanadiana",
            "Ifanirea",
            "Ifarantsa",
            "Ifasina I",
            "Ifasina II",
            "Ifatsy",
            "Ifotaka",
            "Ihadilanana",
            "Ihazoara",
            "Ihorombe",
            "Ihosy",
            "Ikalalao",
            "Ikalamavony",
            "Ikongo",
            "Ilafy",
            "Ilaka Centre",
            "Ilaka Est",
            "Ilakaka",
            "Ilakatra",
            "Ilemby",
            "Imanombo",
            "Imerimandroso",
            "Imerina Imady",
            "Imerintsiatosika",
            "Imito",
            "Imongy",
            "Imorona",
            "Inanantonana",
            "Irina",
            "Isahara",
            "Isaka",
            "Isaka-Ivondro",
            "Isalo",
            "Isoanala",
            "Isorana",
            "Itampolo",
            "Itaosy",
            "Itondy",
            "Itremo",
            "Ivahona",
            "Ivandrika",
            "Ivato",
            "Ivato Aeroport",
            "Ivato Firaisana",
            "Ivoamba",
            "Ivohibe",
            "Ivondro",
            "Ivongo",
            "Ivony Miaramiasa",
            "Jafaro",
            "Jangany",
            "Joffre Ville",
            "Kalafotsy",
            "Kalandy",
            "Kandreho",
            "Karianga",
            "Karimbary",
            "Katsepy",
            "Kelilalina",
            "Keliloha",
            "Kiangara",
            "Kianjandrakefina",
            "Kianjanomby",
            "Kianjavato",
            "Kirano",
            "Kiranomena",
            "Komajia",
            "Kopoky",
            "Lakato",
            "Lalazana",
            "Lanivo",
            "Lanjarivo",
            "Lazarivo",
            "Leanja",
            "Lohafary",
            "Lohariandava",
            "Lohavanana",
            "Lokomby",
            "Longozabe",
            "Lopary",
            "Madiromirafy",
            "Madirovalo",
            "Maevaranohely",
            "Maevatanana",
            "Maevatanana I",
            "Maevatanana II",
            "Mafaijijo",
            "Mahabako",
            "Mahabe",
            "Mahabibo",
            "Mahabo",
            "Mahabo Mananivo",
            "Mahaboboka",
            "Mahaditra",
            "Mahadrodroka",
            "Mahafasa Centre",
            "Mahaiza",
            "Mahajamba Usine",
            "Mahajanga",
            "Mahajeby",
            "Mahalevona",
            "Mahalina",
            "Mahaly",
            "Mahamaibe",
            "Mahambo",
            "Mahanoro",
            "Mahasoa",
            "Mahasoa Est",
            "Mahasoabe",
            "Mahasolo",
            "Mahatalaky",
            "Mahatsara",
            "Mahatsara Iefaka",
            "Mahatsara Sud",
            "Mahatsinjo",
            "Mahatsinjo Est",
            "Mahatsinjony",
            "Mahavanona",
            "Mahavatse I",
            "Mahavatse II",
            "Mahavelo",
            "Mahavelona",
            "Mahavelona Foulpointe",
            "Mahavoky Nord",
            "Mahazina Ambohipierenana",
            "Mahazoarivo",
            "Mahazoarivo Avarabohitra",
            "Mahazoma",
            "Mahazony",
            "Mahela",
            "Mahereza",
            "Maheriraty",
            "Maherivaratra",
            "Mahitsy",
            "Maintinandry",
            "Maintirano",
            "Maitsokely",
            "Malaimbandy",
            "Malakialina",
            "Maliorano",
            "Mampikony I",
            "Mampikony II",
            "Manakambahiny Andrefana",
            "Manakambahiny Antsinanana",
            "Manakana",
            "Manakana Nord",
            "Manakara",
            "Manakompy",
            "Manalalondo",
            "Manalobe",
            "Manambaro",
            "Manambato",
            "Manambidala",
            "Manambina",
            "Manambolo",
            "Manambolosy",
            "Manambondro",
            "Manambotra Atsimo",
            "Manamisoa",
            "Manampaneva",
            "Manampatrana",
            "Mananara Avaratra",
            "Mananasy",
            "Manandaza",
            "Manandona",
            "Manandriana",
            "Manandroy",
            "Mananjara",
            "Mananjary",
            "Manantenina",
            "Manaratsandry",
            "Manato",
            "Manazary",
            "Mandabe",
            "Mandialaza",
            "Mandiavato",
            "Mandiso",
            "Mandoto",
            "Mandritsara",
            "Mandromondromotra",
            "Mandronarivo",
            "Mandrosoa",
            "Mandrosohasina",
            "Mandrosonoro",
            "Manerinerina",
            "Maneva",
            "Manevy",
            "Mangabe",
            "Mangamila",
            "Mangaoka",
            "Mangarano",
            "Mangarivotra",
            "Mangataboahangy",
            "Mangatsiotra",
            "Mangidy",
            "Mangindrano",
            "Maniry",
            "Manja",
            "Manjakandriana",
            "Manjakatompo",
            "Manjakavaradrano",
            "Manodidina Ny Gara Ambilombe",
            "Manohisoa",
            "Manolafaka",
            "Manombo Sud",
            "Manompana",
            "Manorofify",
            "Mantaly",
            "Mantasoa",
            "Marerano",
            "Maria",
            "Mariarano",
            "Maritampona",
            "Maroadabo",
            "Maroala",
            "Maroalomainty",
            "Maroalopoty",
            "Maroamalona",
            "Maroambihy",
            "Maroantsetra",
            "Maroarivo Ankazomanga",
            "Marofangady",
            "Marofarihy",
            "Marofinaritra",
            "Marofototra",
            "Marofoty",
            "Marogaona",
            "Maroharatra",
            "Maroharona",
            "Marohazo",
            "Marojala",
            "Marokarima",
            "Marokibo",
            "Marokoro",
            "Marolambo",
            "Marolinta",
            "Maromandia",
            "Maromavo",
            "Maromby",
            "Maromiandra",
            "Maromitety",
            "Maromokotra Loky",
            "Marondry",
            "Maropaika",
            "Marosangy",
            "Marosavoa",
            "Maroseranana",
            "Marosoa",
            "Marotandrano",
            "Marotoko",
            "Marotolana",
            "Marotsialeha",
            "Marotsipoy",
            "Marotsiraka",
            "Marovandrika",
            "Marovantaza",
            "Marovato",
            "Marovato Befeno",
            "Marovatolena",
            "Maroviro",
            "Marovitsika Sud",
            "Marovoay",
            "Marovoay Banlieue",
            "Marovoay Sud",
            "Marovoay Ville",
            "Masiaboay",
            "Masianaka",
            "Masindray",
            "Masoarivo",
            "Masomeloka",
            "Matanga",
            "Matsakabanja",
            "Matsohely",
            "Matsondakana",
            "Mavorano",
            "Mazavasoa",
            "Menamaty Iloto",
            "Merikanjaka",
            "Merimandroso",
            "Miadanandriana",
            "Miandrandra",
            "Miandrarivo",
            "Miandrivazo",
            "Miantso",
            "Miantsoarivo",
            "Miarinarivo",
            "Miarinarivo I",
            "Miarinarivo II",
            "Miarinavaratra",
            "Miary Ambohibola",
            "Miary Lamatihy",
            "Miary Taheza",
            "Mihavatsy",
            "Mikoboka",
            "Milamaina",
            "Milanoa",
            "Milenaka",
            "Miorimivalana",
            "Mitanty",
            "Mitsinjo",
            "Mitsinjo Betanimena",
            "Mizilo Gara",
            "Montifeno",
            "Morafeno",
            "Morafeno Bekily",
            "Morafenobe",
            "Moramanga",
            "Morarano",
            "Morarano Chrome",
            "Morarano Gara",
            "Morarano Maritampona",
            "Morondava",
            "Moroteza",
            "Mosorolava",
            "Namohora Iaborano",
            "Namorona",
            "Nanarena Besakoa",
            "Nandihizana",
            "Naninora",
            "Nasandratrony",
            "Nato",
            "Niarovana Caroline",
            "Niarovana Marosampanana",
            "Nihaonana",
            "Niherenana",
            "Nikoly",
            "Nosiarina",
            "Nosibe",
            "Nosifeno",
            "Nosy Ambositra",
            "Nosy Varika",
            "Onilahy",
            "Onjatsy",
            "Pont Sofia",
            "Port Berge",
            "Port Berge II",
            "Ramainandro",
            "Rambolamasoandro Andranomiely",
            "Ramena",
            "Ranobe",
            "Ranohira",
            "Ranomafana",
            "Ranomafana Est",
            "Ranomainty",
            "Ranomena",
            "Ranopiso",
            "Ranotsara Nord",
            "Ranotsara Sud",
            "Ranovao",
            "Rantabe",
            "Sabotsy Ambohitromby",
            "Sabotsy Anjiro",
            "Sabotsy Manjakavahoaka",
            "Sabotsy Namatoana",
            "Sabotsy Namehana",
            "Sadabe",
            "Sadjoavato",
            "Sahakevo",
            "Sahalanona",
            "Sahalava",
            "Sahamadio",
            "Sahamadio Fisakana",
            "Sahamamy",
            "Sahamatevina",
            "Sahambala",
            "Sahambano",
            "Sahambavy",
            "Sahanambohitra",
            "Sahanivotry Manandona",
            "Saharefo",
            "Sahasinaka",
            "Sahatavy",
            "Sahatona",
            "Sahatsiho Ambohimanjaka",
            "Sahavato",
            "Sahave",
            "Saint Augustin",
            "Sainte Marie",
            "Saivaza",
            "Sakalalina",
            "Sakamahily",
            "Sakamasay",
            "Sakaraha",
            "Sakaramy",
            "Sakena",
            "Sakoamadinika",
            "Sakoana",
            "Salobe",
            "Sambaina",
            "Sambava Cu",
            "Sampona",
            "Sandrakatsy",
            "Sandrandahy",
            "Sandravinany",
            "Sandrohy",
            "Sarahandrano",
            "Saranambana",
            "Sarisambo",
            "Sarobaratra",
            "Sarobaratra Ifanja",
            "Sarodrano",
            "Saromaona",
            "Satrokala",
            "Savana",
            "Sendrisoa",
            "Sihanamaro",
            "Sitampiky",
            "Soahany",
            "Soaindrana",
            "Soakibany",
            "Soalala",
            "Soalandy",
            "Soalara Sud",
            "Soalazaina",
            "Soaloka",
            "Soamahamanina",
            "Soamalaza Mahatsinjo",
            "Soamanonga",
            "Soamanova",
            "Soamatasy",
            "Soanenga",
            "Soanierana",
            "Soanierana Ivongo",
            "Soanindrariny",
            "Soaserana",
            "Soatanana",
            "Soavary",
            "Soavimbazaha",
            "Soavina",
            "Soavinandriana",
            "Solila",
            "Sorombo",
            "Taindambo",
            "Talata Ampano",
            "Talata Angavo",
            "Talata Vohimena",
            "Talata Volonondry",
            "Talatamaty",
            "Tambohorano",
            "Tameantsoa",
            "Tamponala",
            "Tanakambana",
            "Tanamarina Bekisopa",
            "Tanamarina Sakay",
            "Tanamary",
            "Tanambao Besakay",
            "Tanambao Daoud",
            "Tanambao Haut",
            "Tanambao I",
            "Tanambao II Tsf Nord",
            "Tanambao Marivorahona",
            "Tanambao Rabemanana",
            "Tanambao V",
            "Tanambao Vahatrakaka",
            "Tanambe",
            "Tanana Ambany",
            "Tanana Ambony",
            "Tanananifololahy",
            "Tanandava",
            "Tanandava Sud",
            "Tandrano",
            "Tangainony",
            "Tanibe",
            "Tanjombato",
            "Tankafatra",
            "Tataho",
            "Tatamalaza",
            "Toamasina Suburbaine",
            "Tolohomiady",
            "Tolongoina",
            "Tomboarivo",
            "Tongobory",
            "Tovona",
            "Trangahy",
            "Tranomaro",
            "Tranoroa",
            "Tranovaho",
            "Tratramarina",
            "Tritriva",
            "Tsarabaria",
            "Tsarahasina",
            "Tsarahonenana",
            "Tsarahonenana Sahanivotry",
            "Tsarajomoka",
            "Tsaramandroso",
            "Tsaramasoandro",
            "Tsaraotana",
            "Tsararano",
            "Tsararova",
            "Tsarasambo",
            "Tsarasaotra",
            "Tsaratanana",
            "Tsaratanana I",
            "Tsaravary",
            "Tsaravinany",
            "Tsarazaza",
            "Tsiafahy",
            "Tsiafajavona Ankaratra",
            "Tsiamalao",
            "Tsianisiha",
            "Tsianofana",
            "Tsiately",
            "Tsiatosika",
            "Tsihombe",
            "Tsikolaky",
            "Tsimafana",
            "Tsimananada",
            "Tsiningia",
            "Tsinjoarivo",
            "Tsinjoarivo 22",
            "Tsinjoarivo Imanga",
            "Tsinjomitondraka",
            "Tsirandrany",
            "Tsiroanomandidy Fihaonana",
            "Tsitondroina",
            "Tsivangiana",
            "Tsivory",
            "Valabetokana",
            "Vangaindrano",
            "Vanono",
            "Vasiana",
            "Vatana",
            "Vatanato",
            "Vatohandrina",
            "Vatolatsaka",
            "Vatomandry",
            "Vatosola",
            "Vavatenina",
            "Veromanga",
            "Viliahazo",
            "Vinaninkarena",
            "Vinaninony Atsimo",
            "Vinanitelo",
            "Vinanivao",
            "Vinany",
            "Vinany Andakatanikely",
            "Vodiriana",
            "Vohemar",
            "Vohibato Ouest",
            "Vohiboreka",
            "Vohidahy",
            "Vohidroa",
            "Vohilany",
            "Vohilava",
            "Vohilengo",
            "Vohimalaza",
            "Vohimanga",
            "Vohimanitra",
            "Vohimarina",
            "Vohimary",
            "Vohimasina Nord",
            "Vohimasina Sud",
            "Vohimasy",
            "Vohimena",
            "Vohindava",
            "Vohipaho",
            "Vohipeno",
            "Vohipeno Razanaka",
            "Vohiposa",
            "Vohitany",
            "Vohitrafeno",
            "Vohitrambo",
            "Vohitrandriana",
            "Vohitranivona",
            "Vohitrarivo",
            "Vohitrindry",
            "Vohitromby",
            "Vohitsaoka",
            "Vohitsara",
            "Voloina",
            "Vondrozo",
            "Zazafotsy",
            "Zoma Bealoka"});
            this.townAdd.ItemsAppearance.Parent = this.townAdd;
            this.townAdd.Location = new System.Drawing.Point(108, 55);
            this.townAdd.Name = "townAdd";
            this.townAdd.ShadowDecoration.Parent = this.townAdd;
            this.townAdd.Size = new System.Drawing.Size(343, 36);
            this.townAdd.TabIndex = 17;
            // 
            // descripAdd
            // 
            this.descripAdd.AcceptsReturn = true;
            this.descripAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.descripAdd.BorderRadius = 5;
            this.descripAdd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.descripAdd.DefaultText = "";
            this.descripAdd.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.descripAdd.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.descripAdd.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.descripAdd.DisabledState.Parent = this.descripAdd;
            this.descripAdd.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.descripAdd.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.descripAdd.FocusedState.Parent = this.descripAdd;
            this.descripAdd.Font = new System.Drawing.Font("Segoe UI", 11F);
            this.descripAdd.HoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.descripAdd.HoverState.Parent = this.descripAdd;
            this.descripAdd.Location = new System.Drawing.Point(108, 250);
            this.descripAdd.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.descripAdd.Multiline = true;
            this.descripAdd.Name = "descripAdd";
            this.descripAdd.PasswordChar = '\0';
            this.descripAdd.PlaceholderText = "";
            this.descripAdd.SelectedText = "";
            this.descripAdd.ShadowDecoration.Parent = this.descripAdd;
            this.descripAdd.Size = new System.Drawing.Size(343, 155);
            this.descripAdd.TabIndex = 18;
            // 
            // priceAdd
            // 
            this.priceAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.priceAdd.BackColor = System.Drawing.Color.Transparent;
            this.priceAdd.BorderRadius = 5;
            this.priceAdd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.priceAdd.DisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(208)))), ((int)(((byte)(208)))));
            this.priceAdd.DisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(226)))), ((int)(((byte)(226)))));
            this.priceAdd.DisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(138)))), ((int)(((byte)(138)))));
            this.priceAdd.DisabledState.Parent = this.priceAdd;
            this.priceAdd.DisabledState.UpDownButtonFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(177)))), ((int)(((byte)(177)))), ((int)(((byte)(177)))));
            this.priceAdd.DisabledState.UpDownButtonForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(203)))), ((int)(((byte)(203)))));
            this.priceAdd.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.priceAdd.FocusedState.Parent = this.priceAdd;
            this.priceAdd.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.priceAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(137)))), ((int)(((byte)(149)))));
            this.priceAdd.Location = new System.Drawing.Point(108, 153);
            this.priceAdd.Maximum = new decimal(new int[] {
            -727379969,
            232,
            0,
            0});
            this.priceAdd.Name = "priceAdd";
            this.priceAdd.ShadowDecoration.Parent = this.priceAdd;
            this.priceAdd.Size = new System.Drawing.Size(343, 36);
            this.priceAdd.TabIndex = 20;
            this.priceAdd.UpDownButtonFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.priceAdd.UpDownButtonForeColor = System.Drawing.Color.Yellow;
            // 
            // categoryAdd
            // 
            this.categoryAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.categoryAdd.BackColor = System.Drawing.Color.Transparent;
            this.categoryAdd.BorderRadius = 5;
            this.categoryAdd.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.categoryAdd.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.categoryAdd.FocusedColor = System.Drawing.Color.Empty;
            this.categoryAdd.FocusedState.Parent = this.categoryAdd;
            this.categoryAdd.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.categoryAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.categoryAdd.FormattingEnabled = true;
            this.categoryAdd.HoverState.Parent = this.categoryAdd;
            this.categoryAdd.ItemHeight = 30;
            this.categoryAdd.Items.AddRange(new object[] {
            "Apartment",
            "Villa",
            "Penthouse",
            "Shaw?"});
            this.categoryAdd.ItemsAppearance.Parent = this.categoryAdd;
            this.categoryAdd.Location = new System.Drawing.Point(108, 201);
            this.categoryAdd.Name = "categoryAdd";
            this.categoryAdd.ShadowDecoration.Parent = this.categoryAdd;
            this.categoryAdd.Size = new System.Drawing.Size(343, 36);
            this.categoryAdd.TabIndex = 22;
            // 
            // addHome
            // 
            this.AcceptButton = this.searchButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(463, 480);
            this.Controls.Add(this.categoryAdd);
            this.Controls.Add(this.priceAdd);
            this.Controls.Add(this.descripAdd);
            this.Controls.Add(this.townAdd);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.searchButton);
            this.Controls.Add(this.addressAdd);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "addHome";
            this.Text = "addHome";
            this.Load += new System.EventHandler(this.addHome_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.priceAdd)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private Guna.UI2.WinForms.Guna2TextBox addressAdd;
        private Guna.UI2.WinForms.Guna2Button searchButton;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private Guna.UI2.WinForms.Guna2ComboBox townAdd;
        private Guna.UI2.WinForms.Guna2TextBox descripAdd;
        private Guna.UI2.WinForms.Guna2NumericUpDown priceAdd;
        private Guna.UI2.WinForms.Guna2ComboBox categoryAdd;
    }
}